# Generated by Django 5.0.4 on 2024-05-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                ("cpu", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("catalog.product",),
        ),
    ]
